-- Insert sample destinations
INSERT INTO destinations (name, country, description, image_url, rating, price_range, best_time, highlights, category) VALUES
('Paris', 'France', 'The City of Light, famous for its art, fashion, gastronomy and culture.', '/placeholder.svg?height=300&width=400', 4.8, '$$$', 'April-June, September-October', ARRAY['Eiffel Tower', 'Louvre Museum', 'Notre-Dame Cathedral', 'Champs-Élysées'], 'Cultural'),
('Tokyo', 'Japan', 'A bustling metropolis blending traditional culture with cutting-edge technology.', '/placeholder.svg?height=300&width=400', 4.7, '$$$$', 'March-May, September-November', ARRAY['Shibuya Crossing', 'Tokyo Tower', 'Senso-ji Temple', 'Tsukiji Fish Market'], 'Urban'),
('Bali', 'Indonesia', 'Tropical paradise known for its beaches, temples, and vibrant culture.', '/placeholder.svg?height=300&width=400', 4.6, '$$', 'April-October', ARRAY['Ubud Rice Terraces', 'Tanah Lot Temple', 'Seminyak Beach', 'Mount Batur'], 'Beach'),
('New York', 'USA', 'The city that never sleeps, offering world-class attractions and experiences.', '/placeholder.svg?height=300&width=400', 4.5, '$$$$', 'April-June, September-November', ARRAY['Statue of Liberty', 'Central Park', 'Times Square', 'Brooklyn Bridge'], 'Urban'),
('Santorini', 'Greece', 'Stunning Greek island famous for its white-washed buildings and sunsets.', '/placeholder.svg?height=300&width=400', 4.9, '$$$', 'April-October', ARRAY['Oia Village', 'Red Beach', 'Akrotiri', 'Fira Town'], 'Beach'),
('Dubai', 'UAE', 'Modern city known for luxury shopping, ultramodern architecture and nightlife.', '/placeholder.svg?height=300&width=400', 4.4, '$$$$', 'November-March', ARRAY['Burj Khalifa', 'Dubai Mall', 'Palm Jumeirah', 'Desert Safari'], 'Luxury');

-- Insert sample hotels
INSERT INTO hotels (name, location, description, image_url, rating, price, original_price, category, amenities, features, availability) VALUES
('Hotel Plaza Athénée', 'Paris, France', 'Luxury hotel on Avenue Montaigne with Eiffel Tower views.', '/placeholder.svg?height=300&width=400', 4.8, 850.00, 1200.00, 'Luxury', ARRAY['Spa', 'Fine Dining', 'Concierge', 'Fitness Center'], ARRAY['Eiffel Tower View', 'Michelin Star Restaurant', 'Designer Shopping'], true),
('Park Hyatt Tokyo', 'Tokyo, Japan', 'Sophisticated hotel in Shinjuku with panoramic city views.', '/placeholder.svg?height=300&width=400', 4.7, 650.00, 800.00, 'Luxury', ARRAY['Spa', 'Pool', 'Business Center', 'Fitness Center'], ARRAY['City Views', 'Traditional Japanese Design', 'Premium Location'], true),
('The Mulia Resort', 'Bali, Indonesia', 'Beachfront resort with stunning ocean views and world-class amenities.', '/placeholder.svg?height=300&width=400', 4.6, 320.00, 450.00, 'Resort', ARRAY['Beach Access', 'Multiple Pools', 'Spa', 'Water Sports'], ARRAY['Ocean View', 'Private Beach', 'Tropical Gardens'], true),
('The Plaza Hotel', 'New York, USA', 'Iconic luxury hotel overlooking Central Park.', '/placeholder.svg?height=300&width=400', 4.5, 750.00, 950.00, 'Luxury', ARRAY['Spa', 'Fine Dining', 'Concierge', 'Business Center'], ARRAY['Central Park View', 'Historic Landmark', 'Premium Shopping'], true),
('Canaves Oia Hotel', 'Santorini, Greece', 'Boutique hotel with infinity pools and caldera views.', '/placeholder.svg?height=300&width=400', 4.9, 580.00, 720.00, 'Boutique', ARRAY['Infinity Pool', 'Spa', 'Fine Dining', 'Concierge'], ARRAY['Caldera View', 'Sunset Views', 'Traditional Architecture'], true),
('Burj Al Arab', 'Dubai, UAE', 'Iconic sail-shaped luxury hotel on its own island.', '/placeholder.svg?height=300&width=400', 4.8, 1200.00, 1500.00, 'Luxury', ARRAY['Private Beach', 'Helicopter Pad', 'Butler Service', 'Multiple Restaurants'], ARRAY['Iconic Architecture', 'All-Suite Accommodation', 'Ultra-Luxury'], true);
